apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudprofile.yaml
- controller-registration.yaml
- project.yaml
- secret-backup.yaml
- secretbinding.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-cilium/v1.22.0/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.31.1/example/controller-registration.yaml

patchesStrategicMerge:
- patch-controller-registrations.yaml
- patch-controller-deployment.yaml

patches:
- target:
    group: core.gardener.cloud
    kind: ControllerRegistration
    name: provider-local
  patch: |
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-seed
        lifecycle:
          reconcile: BeforeKubeAPIServer
          delete: AfterKubeAPIServer
          migrate: AfterKubeAPIServer
        workerlessSupported: true
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-shoot
        workerlessSupported: true
