images:
  grafana: image-repository:image-tag

ingress:
  class: nginx
  hosts:
  - hostName: g.seed-1.example.com
    secretName: grafana-tls
  # admin : admin base64 encoded
  authSecretName: auth-secret-name
replicas: 1
ports:
  prometheus: 9090
  grafana: 3000

vpaEnabled: false
extensions:
  dashboards: ""

sni:
  enabled: false

nodeLocalDNS:
  enabled: false

reversedVPN:
  highAvailabilityEnabled: false

workerless: false
