dependencies:
- name: blackbox-exporter
  repository: http://localhost:10191
  version: 0.1.0
  condition: global.hasWorkers
- name: node-exporter
  repository: http://localhost:10191
  version: 0.1.0
  condition: global.hasWorkers
- name: prometheus-shoot
  repository: http://localhost:10191
  version: 0.1.0
