#TODO(shafeeqes): Delete this Helm chart in a future version.
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpn-shoot.certs.name" . }}
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
