# TODO(shafeeqes): Delete this Helm chart in a future version.
---
{{- if not .Values.reversedVPN.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-shoot
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}