{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: vpn-shoot
  namespace: {{ .Release.Namespace }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
