# TODO(shafeeqes): Delete this Helm chart in a future version.
---
apiVersion: {{ template "rbacversion" . }}
kind: ClusterRole
metadata:
  name: system:gardener.cloud:vpn-seed
  annotations:
    resources.gardener.cloud/mode: Ignore
---
apiVersion: {{ template "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: system:gardener.cloud:vpn-seed
  annotations:
    resources.gardener.cloud/mode: Ignore
