rule_files:
- ../rules/worker/kube-pods.rules.yaml

evaluation_interval: 30s

tests:
- interval: 30s
  input_series:
  # KubePodPendingShoot
  - series: 'kube_pod_status_phase{phase="Pending", type="shoot", pod="pendingPod"}'
    values: '1+0x120'
  - series: 'kube_pod_labels{label_origin="gardener", pod="pendingPod"}'
    values: '1+0x120'
  # KubePodPendingControlPlane
  - series: 'kube_pod_status_phase{phase="Pending", type="seed", pod="pendingPod"}'
    values: '1+0x60'
  # KubePodNotReadyShoot
  - series: 'kube_pod_status_ready{condition="true", type="shoot", pod="notReadyPod"}'
    values: '0+0x120'
  - series: 'kube_pod_labels{label_origin="gardener", pod="notReadyPod"}'
    values: '1+0x120'
  # KubePodNotReadyControlPlane
  - series: 'kube_pod_status_ready{condition="true", type="seed", pod="cpPodNotReady"}'
    values: '0+0x60'
  alert_rule_test:
  - eval_time: 1h
    alertname: KubePodPendingShoot
    exp_alerts:
    - exp_labels:
        service: kube-kubelet
        severity: warning
        visibility: owner
        type: shoot
        pod: pendingPod
        phase: Pending
      exp_annotations:
        description: Pod pendingPod is stuck in "Pending" state for more than 1 hour.
        summary: Shoot pod stuck in "Pending" state
  - eval_time: 30m
    alertname: KubePodPendingControlPlane
    exp_alerts:
    - exp_labels:
        service: kube-kubelet
        severity: warning
        visibility: operator
        type: seed
        pod: pendingPod
        phase: Pending
      exp_annotations:
        description: Pod pendingPod is stuck in "Pending" state for more than 30 minutes.
        summary: Control plane pod stuck in "Pending" state
  - eval_time: 1h
    alertname: KubePodNotReadyShoot
    exp_alerts:
    - exp_labels:
        service: kube-kubelet
        severity: warning
        visibility: owner
        type: shoot
        pod: notReadyPod
        condition: true
      exp_annotations:
        description: Pod notReadyPod is not ready for more than 1 hour.
        summary: Shoot pod is in a not ready state
  - eval_time: 30m
    alertname: KubePodNotReadyControlPlane
    exp_alerts:
    - exp_labels:
        service: kube-kubelet
        severity: warning
        visibility: operator
        type: seed
        pod: cpPodNotReady
        condition: true
      exp_annotations:
        description: Pod cpPodNotReady is not ready for more than 30 minutes.
        summary: Control plane pod is in a not ready state
